name: Build SBOM

on:
  workflow_call:

jobs:
  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7
      - uses: moonrepo/setup-rust@v1
        with:
          bins: cargo-cyclonedx, wkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: WKG_CONFIG_FILE=wkg-registry.toml wkg wit fetch --type wit
        working-directory: act-cli
      - name: Generate CycloneDX SBOM
        run: cargo cyclonedx -f json --target all
      - uses: actions/upload-artifact@v7
        with:
          name: sbom
          path: "**/*.cdx.json"
          if-no-files-found: error
