name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check & Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: moonrepo/setup-rust@v1
        with:
          channel: nightly
          components: clippy
          bins: wit-deps-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: wit-deps
      - run: cargo check
      - run: cargo clippy -- -D warnings

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: moonrepo/setup-rust@v1
        with:
          channel: nightly
          components: rustfmt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo fmt -- --check

  test:
    name: Test
    needs: [check, fmt]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: moonrepo/setup-rust@v1
        with:
          channel: nightly
          bins: wit-deps-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: wit-deps
      - run: cargo test

  build:
    needs: [check, fmt]
    uses: ./.github/workflows/build.yml

  build-pypi:
    needs: [check, fmt]
    uses: ./.github/workflows/build-pypi.yml

  build-npm:
    needs: build
    uses: ./.github/workflows/build-npm.yml
